# Generated by Django 5.2.1 on 2025-05-08 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_country_company_country_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('characteristics', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('COP', 'Colombian Peso'), ('MXN', 'Mexican Peso'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('AUD', 'Australian Dollar')], default='COP', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this product should be treated as active.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the product was created.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the product was deactivated (soft deleted).', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='company.company')),
            ],
        ),
    ]
