# Generated by Django 5.2.1 on 2025-05-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the user was deactivated (soft deleted).', null=True),
        ),
    ]
