# Generated by Django 5.2.1 on 2025-05-08 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of the product in stock.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product.', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this inventory item is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the inventory item was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the inventory item was last updated.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='product.product')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
            },
        ),
    ]
