# Generated by Django 5.2.1 on 2025-05-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_created_by_inventoryitem_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='alert',
            field=models.BooleanField(default=False, help_text='Indicates if stock is below the alert threshold (5 units).'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale')], default='purchase', help_text="Type of transaction: 'purchase' for adding stock, 'sale' for reducing stock.", max_length=10),
        ),
    ]
