# Generated by Django 5.2.1 on 2025-05-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_alert_inventoryitem_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='price',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Profit from the transaction', max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Purchase price of the product.', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Sale price of the product.', max_digits=10),
            preserve_default=False,
        ),
    ]
