# Generated by Django 5.2.1 on 2025-05-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_inventoryitem_price_inventoryitem_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price of the product.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sale price of the product.', max_digits=10, null=True),
        ),
    ]
